package com.m4rc310.rcp.graphql.i18n;

public class M {
	public String preferenceTitleServer;
	public String preferenceIsLocalServer;
	public String preferenceUrlLocalServer;
	public String preferenceUrlServer;
	public String preferenceUrlLocalWebsocket;
	public String preferenceUrlWebsocket;
	
	public String preferenceConnectionParams;
	public String preferenceNameStation;
	public String labelAutoGenerated;
}
